### ISSUE TITLE
panic: dial tcp [::1]:1883: getsockopt: connection refused

### ISSUE THREAD

**Issue by gazzer82** [happy-bubbles/presence#3]
Just running through the setup process on the Wiki, and the process is failing to start with the following errors, any idea what could be causing the issue, port 1883 is open?

```
pi@raspberrypi:~ $ /home/pi/presence/presence -http_host_path=0.0.0.0:5555
panic: dial tcp [::1]:1883: getsockopt: connection refused

goroutine 1 [running]:
panic(0x390328, 0x10768750)
	/code/go/go/src/runtime/panic.go:481 +0x330
main.main()
	/code/happy-bubbles/presence-gh/main.go:608 +0x5d4

```

**Comment by gazzer82** [comment]
Ok, so it seems the install script installs and user Mosquito, I already have Mosquito installed, but running on a different port. I have now manually updated the port to 1883, and I no longer get that error, but I now get the following one, any ideas?

```
● presence.service - presence
   Loaded: loaded (/etc/systemd/system/presence.service; enabled)
   Active: failed (Result: start-limit) since Tue 2017-04-18 14:27:25 UTC; 19s ago
  Process: 1037 ExecStart=/home/pi/presence/presence -http_host_path=0.0.0.0:5555 (code=exited, status=2)
 Main PID: 1037 (code=exited, status=2)

Apr 18 14:27:25 raspberrypi presence[1037]: main.main()
Apr 18 14:27:25 raspberrypi presence[1037]: /code/happy-bubbles/presence-gh/main.go:647 +0xc00
Apr 18 14:27:25 raspberrypi systemd[1]: presence.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 18 14:27:25 raspberrypi systemd[1]: Unit presence.service entered failed state.
Apr 18 14:27:25 raspberrypi systemd[1]: presence.service holdoff time over, scheduling restart.
Apr 18 14:27:25 raspberrypi systemd[1]: Stopping presence...
Apr 18 14:27:25 raspberrypi systemd[1]: Starting presence...
Apr 18 14:27:25 raspberrypi systemd[1]: presence.service start request repeated too quickly, refusing to start.
Apr 18 14:27:25 raspberrypi systemd[1]: Failed to start presence.
Apr 18 14:27:25 raspberrypi systemd[1]: Unit presence.service entered failed state.
```

**Comment by gazzer82** [comment]
If I try to run the command manually I get the following:

```
pi@raspberrypi:~/downloads $ /home/pi/presence/presence -http_host_path=0.0.0.0:5555
 _   _    _    ____  ______   __  ____  _   _ ____  ____  _     _____ ____
| | | |  / \  |  _ \|  _ \ \ / / | __ )| | | | __ )| __ )| |   | ____/ ___|
| |_| | / _ \ | |_) | |_) \ V /  |  _ \| | | |  _ \|  _ \| |   |  _| \___ \
|  _  |/ ___ \|  __/|  __/ | |   | |_) | |_| | |_) | |_) | |___| |___ ___) |
|_| |_/_/   \_\_|   |_|    |_|   |____/ \___/|____/|____/|_____|_____|____/

 
CONNECTED TO MQTT

 
Visit http://0.0.0.0:5555 on your browser to see the web interface

 
EOF
panic: the Client has not yet connected to the Server

goroutine 1 [running]:
panic(0x36dc10, 0x1076a688)
	/code/go/go/src/runtime/panic.go:481 +0x330
main.main()
	/code/happy-bubbles/presence-gh/main.go:647 +0xc00
```

**Comment by nemik** [comment]
@gazzer82 sorry to hear you're having trouble with it. Can you subscribe to topics on your MQTT normally with the `mosquitto_sub` command?

The Presence server is trying to subscribe to `happy-bubbles/ble/#` where it crashed for you. Try to subscribe to it on port 1883 with no username/password using `mosquitto_sub` to figure out what might be happening.

But if you need a special port or something, run `/home/pi/presence/presence -h` and you'll see other command-line options you can pass to it to tell it to connect to a different server or port if you want.
