### ISSUE TITLE
Windows Builds dont work on latest patchlevels Windows 10

### ISSUE THREAD

**Issue by mruiter** [happy-bubbles/presence#7]
panic: dial tcp [::1]:1883: connectex: No connection could be made because the target machine actively refused it.

goroutine 1 [running]:
panic(0x83fd00, 0xc08200c9b0)
        /code/go/go/src/runtime/panic.go:481 +0x3f4
main.main()
        /code/happy-bubbles/presence-gh/main.go:616 +0x6cc

**Comment by mruiter** [comment]
Nevermind -h gives options :)
